import { MasterDataEndpointConfig, MasterDataKey } from "@/types/master-data";

export const masterDataMap: Record<MasterDataKey, MasterDataEndpointConfig> = {
  "price-list": {
    key: "price-list",
    label: "Price List",
    sourcePath: "/PriceLists",
    targetPath: "/master/price-list",
    sapPostPath: "/PriceLists",
    syncTargetMode: "per-record",
    notes: "Old .NET: SavePriceList_SP / tblRefPriceListPrices_insert",
  },
  periods: {
    key: "periods",
    label: "Periods",
    sourcePath: "/Periods",
    targetPath: "/master/periods",
    sapPostPath: "/Periods",
    sapUpsertKeyField: "PeriodCode",
    syncTargetMode: "per-record",
    notes: "Old .NET: SavePeriods_SP / tblRefPeriods_Insert / OFPR",
  },
  currency: {
    key: "currency",
    label: "Currencies",
    sourcePath: "/Currencies",
    targetPath: "/master/currency",
    syncTargetMode: "none",
    notes: "Old .NET: SaveCurrency_SP / tblRefCurrency_Insert",
  },
  currencies: {
    key: "currencies",
    label: "Currencies",
    sourcePath: "/Currencies",
    targetPath: "/master/currency",
    syncTargetMode: "none",
    notes: "Alias for currency",
  },
  customer: {
    key: "customer",
    label: "Customers",
    sourcePath: "/BusinessPartners?$filter=CardType eq 'C'",
    targetPath: "/master/customer",
    sapPostPath: "/BusinessPartners",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveCustomer_SP / tblRefCustomer_Insert",
  },
  "currency-rates": {
    key: "currency-rates",
    label: "Currency Rates",
    sourcePath: "/SBOBobService_GetCurrencyRate",
    targetPath: "/master/currency-rates",
    sapPostPath: "/SBOBobService_SetCurrencyRate",
    syncTargetMode: "bulk",
    notes: "Old .NET: SaveCurrencyRates_SP / tblRefCurrencyRate_Insert",
  },
  "customer-currencies": {
    key: "customer-currencies",
    label: "Customer Currencies",
    sourcePath: "/BusinessPartners?$select=CardCode,Currency&$filter=CardType eq 'C'",
    targetPath: "/master/customer-currencies",
    syncTargetMode: "none",
    notes: "Old .NET: SaveCurrency_Customerwise_SP / tblRefCustomer_Currency_Insert",
  },
  item: {
    key: "item",
    label: "Items",
    sourcePath: "/Items",
    targetPath: "/master/item",
    sapPostPath: "/Items",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveItem_SP / tblRefItem_Insert",
  },
  "item-warehouses": {
    key: "item-warehouses",
    label: "Item Warehouses",
    sourcePath: "/Items?$select=ItemCode,ItemWarehouseInfoCollection",
    targetPath: "/master/item-warehouses",
    syncTargetMode: "bulk",
    notes: "Old .NET: SaveItemWarehouses_SP / tblRefItem_WH_Insert",
  },
  "warehouse-master": {
    key: "warehouse-master",
    label: "Warehouse Master",
    sourcePath: "/Warehouses",
    targetPath: "/master/warehouse",
    sapPostPath: "/Warehouses",
    sapUpsertKeyField: "WarehouseCode",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveWareHouseMaster_SP / tblWhseMst_insert",
  },
  warehouses: {
    key: "warehouses",
    label: "Warehouses",
    sourcePath: "/Warehouses",
    targetPath: "/master/warehouse",
    sapPostPath: "/Warehouses",
    sapUpsertKeyField: "WarehouseCode",
    syncTargetMode: "per-record",
    notes: "Alias for warehouse-master",
  },
  "sales-rep": {
    key: "sales-rep",
    label: "Sales Representatives",
    sourcePath: "/SalesPersons",
    targetPath: "/master/sales-rep",
    sapPostPath: "/SalesPersons",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveSaleRep_SP / tblRefSalesRep_Insert",
  },
  project: {
    key: "project",
    label: "Projects",
    sourcePath: "/Projects",
    targetPath: "/master/project",
    sapPostPath: "/Projects",
    syncTargetMode: "per-record",
    notes: "Old .NET: Save_Projects_SP / tblRefProject_Insert",
  },
  uom: {
    key: "uom",
    label: "Units of Measure",
    sourcePath: "/UnitOfMeasurements",
    targetPath: "/master/uom",
    sapPostPath: "/UnitOfMeasurements",
    sapUpsertKeyField: "UoMCode",
    syncTargetMode: "per-record",
    notes: "Old .NET: Save_UOM_SP / tblRefUnits_insert",
  },
  "uom-conversion": {
    key: "uom-conversion",
    label: "UOM Conversion",
    sourcePath: "/UnitOfMeasurementGroups",
    targetPath: "/master/uom-conversion",
    syncTargetMode: "bulk",
    notes: "Old .NET: Save_UOM_Convertion_SP / tblRefUOMConverstion_insert",
  },
  "uom-group": {
    key: "uom-group",
    label: "UOM Group",
    sourcePath: "/UnitOfMeasurementGroups",
    targetPath: "/master/uom-group",
    sapPostPath: "/UnitOfMeasurementGroups",
    sapUpsertKeyField: "Code",
    syncTargetMode: "per-record",
    notes: "Old .NET: Save_UOM_Group_SP / tblRefUOMGroup_Insert",
  },
  vendor: {
    key: "vendor",
    label: "Vendors",
    sourcePath: "/BusinessPartners?$filter=CardType eq 'S'",
    targetPath: "/master/vendor",
    sapPostPath: "/BusinessPartners",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveVendor_SP / tblRefVendor_Insert",
  },
  "distribution-rules": {
    key: "distribution-rules",
    label: "Distribution Rules",
    sourcePath: "/DistributionRules",
    targetPath: "/master/distribution-rules",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveDistribution_SP / tblRefDestributionRules_Insert",
  },
  accounts: {
    key: "accounts",
    label: "Chart of Accounts",
    sourcePath: "/ChartOfAccounts",
    targetPath: "/master/accounts",
    sapPostPath: "/ChartOfAccounts",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveAccount_SP / tblRefAccounts_Insert",
  },
  "tax-codes": {
    key: "tax-codes",
    label: "Tax Codes",
    sourcePath: "/VatGroups?$filter=Account ne ''",
    targetPath: "/master/tax-codes",
    sapPostPath: "/VatGroups",
    sapUpsertKeyField: "Code",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveTaxCodes_SP / tblRefVATCodes_Insert / OVTG where Account <> ''",
  },
  "login-users": {
    key: "login-users",
    label: "Login Users",
    sourcePath: "/Users",
    targetPath: "/master/login-users",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveLoginUser_SP / Login_Insert",
  },
  users: {
    key: "users",
    label: "Users",
    sourcePath: "/Users",
    targetPath: "/master/login-users",
    syncTargetMode: "per-record",
    notes: "Alias for login-users",
  },
  bank: {
    key: "bank",
    label: "Bank",
    sourcePath: "/Banks",
    targetPath: "/master/bank",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveBank_SP / tblRefBank_Insert",
  },
  banks: {
    key: "banks",
    label: "Banks",
    sourcePath: "/Banks",
    targetPath: "/master/bank",
    syncTargetMode: "per-record",
    notes: "Alias for bank",
  },
  branch: {
    key: "branch",
    label: "Branch",
    sourcePath: "/Branches",
    targetPath: "/master/branch",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveBranch_SP / tblRefBranch_Insert",
  },
  branches: {
    key: "branches",
    label: "Branches",
    sourcePath: "/Branches",
    targetPath: "/master/branch",
    syncTargetMode: "per-record",
    notes: "Alias for branch",
  },
  "serial-numbers": {
    key: "serial-numbers",
    label: "Serial Numbers",
    sourcePath: "/SerialNumberDetails",
    targetPath: "/master/serial-numbers",
    syncTargetMode: "bulk",
    notes: "Old .NET: SaveSN_SP / tblRefItem_SN_insert",
  },
  "item-group": {
    key: "item-group",
    label: "Item Group",
    sourcePath: "/ItemGroups",
    targetPath: "/master/item-group",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveItemGroup_SP / tblRefItemGroups_Insert",
  },
  "item-groups": {
    key: "item-groups",
    label: "Item Groups",
    sourcePath: "/ItemGroups",
    targetPath: "/master/item-group",
    syncTargetMode: "per-record",
    notes: "Alias for item-group",
  },
  "item-group-accounts": {
    key: "item-group-accounts",
    label: "Item Group Accounts",
    sourcePath: "/ItemGroups?$select=Number,InventoryAccount,CostAccount,WipAccount",
    targetPath: "/master/item-group-accounts",
    syncTargetMode: "per-record",
    notes: "Old .NET: SaveItemGroup_Acc_SP / tblRefItemGroups_Acc_Insert",
  },
};

export function getMasterDataConfig(key: string): MasterDataEndpointConfig | null {
  return masterDataMap[key as MasterDataKey] ?? null;
}

export function listMasterDataConfigs(): MasterDataEndpointConfig[] {
  return Object.values(masterDataMap);
}
