import { TransactionEndpointConfig, TransactionKey } from "@/types/transaction";

export const transactionMap: Record<TransactionKey, TransactionEndpointConfig> = {
  "project-export": {
    key: "project-export",
    label: "Project Posting",
    sapServiceLayerPath: "/Projects",
    pendingHeaderSp: "tblTransEstimateHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransEstimateHeader_BatchPosting_Pending2",
    detailParamName: "EstimateNo",
    detailParamField: "EstimateNo",
    notes: "Old .NET: Get_Pending_Project1",
  },
  "project-posting": {
    key: "project-posting",
    label: "Project Posting",
    sapServiceLayerPath: "/Projects",
    pendingHeaderSp: "tblTransEstimateHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransEstimateHeader_BatchPosting_Pending2",
    detailParamName: "EstimateNo",
    detailParamField: "EstimateNo",
    notes: "Alias for project-export",
  },
  "inventory-issue": {
    key: "inventory-issue",
    label: "Inventory Issue",
    sapServiceLayerPath: "/InventoryGenExits",
    pendingHeaderSp: "tblTransIssueNoteHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransIssueNoteHeader_BatchPosting_Pending2",
    detailParamName: "IssueNo",
    detailParamField: "IssueNo",
    notes: "Old .NET: Get_Pending_InventoryIssues1",
  },
  "inventory-return": {
    key: "inventory-return",
    label: "Inventory Return",
    sapServiceLayerPath: "/InventoryGenEntries",
    pendingHeaderSp: "tblTransReturnNoteHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransReturnNoteHeader_BatchPosting_Pending2",
    detailParamName: "ReturnNo",
    detailParamField: "ReturnNo",
    notes: "Old .NET: Get_Pending_InventoryReturn1",
  },
  "gl-issue": {
    key: "gl-issue",
    label: "GL Issue",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransGLIssueHeader_BatchPosting_Pending1",
    notes: "Old .NET: Get_Pending_GLIssues1",
  },
  "gl-return": {
    key: "gl-return",
    label: "GL Return",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransGLReturnHeader_BatchPosting_Pending1",
    notes: "Old .NET: Get_Pending_GLReturn1",
  },
  "labour-issue": {
    key: "labour-issue",
    label: "Labour Issue",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransJobScheduleManager_Actuals_BatchPosting_Pending1",
    notes: "Old .NET: Get_Pending_LabourIssues1",
  },
  "labour-return": {
    key: "labour-return",
    label: "Labour Return",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransJobScheduleManager_Actuals_Return_BatchPosting_Pending1",
    notes: "Old .NET: Get_Pending_LabourReturn1",
  },
  "supplier-issue": {
    key: "supplier-issue",
    label: "Supplier Invoice",
    sapServiceLayerPath: "/PurchaseInvoices",
    pendingHeaderSp: "tblTransAPIssueHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransAPIssueHeader_BatchPosting_Pending2",
    detailParamName: "APIssueNo",
    detailParamField: "APIssueNo",
    notes: "Old .NET: Get_Pending_SupplierIssues1",
  },
  "supplier-invoice": {
    key: "supplier-invoice",
    label: "Supplier Invoice",
    sapServiceLayerPath: "/PurchaseInvoices",
    pendingHeaderSp: "tblTransAPIssueHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransAPIssueHeader_BatchPosting_Pending2",
    detailParamName: "APIssueNo",
    detailParamField: "APIssueNo",
    notes: "Alias for supplier-issue",
  },
  "supplier-return": {
    key: "supplier-return",
    label: "Supplier Return",
    sapServiceLayerPath: "/PurchaseCreditNotes",
    pendingHeaderSp: "tblTransAPReturn_BatchPosting_Pending1",
    pendingDetailSp: "tblTransAPReturn_BatchPosting_Pending2",
    detailParamName: "APReturnNo",
    detailParamField: "APReturnNo",
    notes: "Old .NET: Get_Pending_SupplierReturn1",
  },
  "subcon-mobilization": {
    key: "subcon-mobilization",
    label: "Sub Contractor Mobilization",
    sapServiceLayerPath: "/PurchaseDownPayments",
    pendingHeaderSp: "tblTransJobHeader_SubCon_BatchPosting_Pending1",
    pendingDetailSp: "tblTransJobHeader_SubCon_BatchPosting_Pending2",
    detailParamName: "SubConMobRefNo",
    detailParamField: "SubConMobRefNo",
    notes: "Old .NET: Get_Pending_SubConJobCard1",
  },
  "subcon-retention": {
    key: "subcon-retention",
    label: "Sub Contractor Retention",
    sapServiceLayerPath: "/PurchaseDownPayments",
    pendingHeaderSp: "tblTransSupplierRetention_BatchPosting_Pending1",
    pendingDetailSp: "tblTransSupplierRetention_BatchPosting_Pending2",
    detailParamName: "SubConMobRefNo",
    detailParamField: "SubConRetRefNo",
    notes: "Old .NET: Get_Pending_SubConRetention1",
  },
  "subcon-invoice": {
    key: "subcon-invoice",
    label: "Sub Contractor Invoice",
    sapServiceLayerPath: "/PurchaseInvoices",
    pendingHeaderSp: "tblTransSupplierInvoiceHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransSupplierInvoiceHeader_BatchPosting_Pending2",
    detailParamName: "InvoiceNo",
    detailParamField: "InvoiceNo",
    notes: "Old .NET: Get_Pending_SubConIssues1",
  },
  "subcon-return": {
    key: "subcon-return",
    label: "Sub Contractor Return",
    sapServiceLayerPath: "/PurchaseCreditNotes",
    pendingHeaderSp: "tblTransSupplierCreditNoteHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransSupplierCreditNoteHeader_BatchPosting_Pending2",
    detailParamName: "CRN_No",
    detailParamField: "CRN_No",
    notes: "Old .NET: Get_Pending_SubConReturn1",
  },
  "customer-mobilization": {
    key: "customer-mobilization",
    label: "Customer Mobilization",
    sapServiceLayerPath: "/DownPayments",
    pendingHeaderSp: "tblTransJobHeader_Customer_BatchPosting_Pending1",
    pendingDetailSp: "tblTransJobHeader_Customer_BatchPosting_Pending2",
    detailParamName: "CustMobRefNo",
    detailParamField: "CustMobRefNo",
    notes: "Old .NET: Get_Pending_CustomerJobCard1",
  },
  "customer-invoice": {
    key: "customer-invoice",
    label: "Customer Invoice",
    sapServiceLayerPath: "/Invoices",
    pendingHeaderSp: "tblTransInvoiceHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransInvoiceHeader_BatchPosting_Pending2",
    detailParamName: "InvoiceNo",
    detailParamField: "InvoiceNo",
    notes: "Old .NET: Get_Pending_CustomerInvoice1",
  },
  "customer-retention": {
    key: "customer-retention",
    label: "Customer Retention",
    sapServiceLayerPath: "/DownPayments",
    pendingHeaderSp: "tblTransCustomerRetention_BatchPosting_Pending1",
    pendingDetailSp: "tblTransCustomerRetention_BatchPosting_Pending2",
    detailParamName: "CustMobRefNo",
    detailParamField: "CustRetRefNo",
    notes: "Old .NET: Get_Pending_CustomerConRetention1",
  },
  "customer-return": {
    key: "customer-return",
    label: "Customer Credit Note",
    sapServiceLayerPath: "/CreditNotes",
    pendingHeaderSp: "tblTransCreditNoteHeader_BatchPosting_Pending1_WIP",
    pendingDetailSp: "tblTransCreditNoteHeader_BatchPosting_Pending2",
    detailParamName: "CRNNo",
    detailParamField: "CRNNo",
    notes: "Old .NET: Get_Pending_CustomerCreditNote1_WIP",
  },
  "customer-credit-note": {
    key: "customer-credit-note",
    label: "Customer Credit Note",
    sapServiceLayerPath: "/CreditNotes",
    pendingHeaderSp: "tblTransCreditNoteHeader_BatchPosting_Pending1_WIP",
    pendingDetailSp: "tblTransCreditNoteHeader_BatchPosting_Pending2",
    detailParamName: "CRNNo",
    detailParamField: "CRNNo",
    notes: "Alias for customer-return",
  },
  "machine-issue": {
    key: "machine-issue",
    label: "Machine Issue",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransMachineIssueHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransMachineIssueHeader_BatchPosting_Pending2",
    detailParamName: "IssueNo",
    detailParamField: "IssueNo",
    notes: "Old .NET: Get_Pending_MachineryIssues1",
  },
  "machine-return": {
    key: "machine-return",
    label: "Machine Return",
    sapServiceLayerPath: "/JournalEntries",
    pendingHeaderSp: "tblTransMachineReturnHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransMachineReturnHeader_BatchPosting_Pending2",
    detailParamName: "ReturnNo",
    detailParamField: "ReturnNo",
    notes: "Old .NET: Get_Pending_MachineryReturns1",
  },
  "inventory-transfer": {
    key: "inventory-transfer",
    label: "Inventory Transfer",
    sapServiceLayerPath: "/StockTransfers",
    pendingHeaderSp: "tblTransWHTransferNoteHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransWHTransferNoteHeader_BatchPosting_Pending2",
    detailParamName: "WHTransNo",
    detailParamField: "WHTransNo",
    notes: "Old .NET: Get_Pending_InventoryWHTransfer1",
  },
  "inventory-po-request": {
    key: "inventory-po-request",
    label: "Purchase Request",
    sapServiceLayerPath: "/PurchaseRequests",
    pendingHeaderSp: "tblTransPORequisitionHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransPORequisitionHeader_BatchPosting_Pending2",
    detailParamName: "PORNo",
    detailParamField: "PORNo",
    notes: "Old .NET: Get_Pending_InventoryPORequest1",
  },
  "purchase-request": {
    key: "purchase-request",
    label: "Purchase Request",
    sapServiceLayerPath: "/PurchaseRequests",
    pendingHeaderSp: "tblTransPORequisitionHeader_BatchPosting_Pending1",
    pendingDetailSp: "tblTransPORequisitionHeader_BatchPosting_Pending2",
    detailParamName: "PORNo",
    detailParamField: "PORNo",
    notes: "Alias for inventory-po-request",
  },
};

export const legacyTransactionSequence: TransactionKey[] = [
  "project-posting",
  "inventory-issue",
  "inventory-return",
  "gl-issue",
  "gl-return",
  "labour-issue",
  "labour-return",
  "supplier-invoice",
  "supplier-return",
  "subcon-mobilization",
  "subcon-retention",
  "subcon-invoice",
  "subcon-return",
  "customer-mobilization",
  "customer-invoice",
  "customer-retention",
  "customer-credit-note",
  "machine-issue",
  "machine-return",
  "inventory-transfer",
  "purchase-request",
];

export function getTransactionConfig(key: string): TransactionEndpointConfig | null {
  return transactionMap[key as TransactionKey] ?? null;
}

export function listTransactionConfigs(): TransactionEndpointConfig[] {
  return Object.values(transactionMap);
}
